### ISSUE TITLE
Domain part depends on persistence implementation, rather on abstraction by interface

### ISSUE THREAD

**Issue by SeWaS** [hbendix/domain-driven-nest#1]
Hello there 👋 

First of all, I genuinely enjoyed the insights you gave into your perspective of DDD in your blogpost on [dev.to](https://dev.to/bendix/applying-domain-driven-design-principles-to-a-nest-js-project-5f7b). Thanks a lot for this!

I checked out this linked repository and happened to stumble across a place in the `domain` part, where I would do a thing differently. It's about this line, for instance:
https://github.com/hbendix/domain-driven-nest/blob/5670d356280ff86c7a189ec24cadbc98baf4234d/src/Domain/User/Update.ts#L8
Instead of making the "domain operations" (`Update.ts` here) depend on `UserRepository`, wouldn't it make more sense to rather make them use `IUserRepository` and let the DI (nestJS in this case) provide the implementation from the `persistence` part?

I think that way the domain only depends on the interfaces it defines by itself. Relates more to what you correctly listed in the post:
> In theory, you should be able to cut and paste your domain layer it into any project (language-dependent) and it should work.

Cheers!

**Comment by hbendix** [comment]
Hey, thanks for the question! It's a really great shout and you know when we first came around to writing our server we had originally tried using Interface injection but we couldn't get it to play ball.  I'm not sure whether this is because it wasn't a working feature at the time or a fault on our behalf. I was of the mind that it was actually a limitation of TypeScript rather than Nest, [outlined here](https://stackoverflow.com/a/53040617/8502078)

Do you have a working example of interface injection I can have a look at? 

Thanks

**Comment by SeWaS** [comment]
Sure. I'd love to open a PR against this repo so you can check it out. But essentially nestJS-DI can only achieve this by using custom token-based providers:

```typescript
// new file PersistanceProvider.ts
export const UserRepositoryProvider: Provider = {
   provide: 'UserRepositoryProvider',
   useClass: UserRepository
};
```

```typescript
// PersistenceModule.ts

@Module({
	imports: [
		UserRepositoryModule,
	],
        providers: [
                 UserRepositoryProvider
        ],
	exports: [
		UserRepositoryProvider
	],
})
export class PersistenceModule {}
```

```typescript
// Update.ts

const UserRepo = () => Inject('UserRepositoryProvider');

@Injectable()
export class Update {
	constructor(
		@UserRepo() private readonly userRepository: IUserRepository,
	) {}

	public async Update(userId: string, toUpdate: Partial<User>): Promise<void> {
		await this.userRepository.UpdateById(userId, toUpdate);
	}
}
```

What we do here is telling nest that with `@UserRepo()` it should provide a particular implementation of `IUserRepository` and in `Update` class we only define the dependency as Interface. Works pretty well in my current project 😃 
That is the way, you are absolutely right that nestJS/typescript cannot use interfaces directly for DI: https://github.com/nestjs/nest/issues/43#issuecomment-300131377.

**Comment by hbendix** [comment]
Ah that's fantastic mate, thanks so much for getting the PR in! I'll have to update the blog post now 😝

**Comment by SeWaS** [comment]
You are very welcome 😃  Happy to help! You blog post was kind of an inspiration for my current product to think more into DDD direction with nest. Keep on posting ;)

**Comment by hbendix** [comment]
Ah, that's brilliant! Will do 😎
